// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqbHWHbhUqsfynZPPm_nNg3XLAe97jDUM',
    appId: '1:701132828293:android:38588b263794e67c6843ec',
    messagingSenderId: '701132828293',
    projectId: 'appnamepp32nutriars',
    storageBucket: 'appnamepp32nutriars.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwIN3fT1QV23vA4_R7QgNIzhnQyZt9fKo',
    appId: '1:701132828293:ios:63b6f75f83cd700d6843ec',
    messagingSenderId: '701132828293',
    projectId: 'appnamepp32nutriars',
    storageBucket: 'appnamepp32nutriars.appspot.com',
    iosBundleId: 'com.example.pp32',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwIN3fT1QV23vA4_R7QgNIzhnQyZt9fKo',
    appId: '1:701132828293:ios:5db1d2dbe187babb6843ec',
    messagingSenderId: '701132828293',
    projectId: 'appnamepp32nutriars',
    storageBucket: 'appnamepp32nutriars.appspot.com',
    iosBundleId: 'com.example.pp32.RunnerTests',
  );
}
